// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  logo: __t.string(),
  tier: __t.string(),
  featured: __t.bool(),
  hazardCounty: __t.string().name("hazard_county"),
  sortOrder: __t.u32().name("sort_order"),
});
