// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  type: __t.string(),
  priority: __t.string(),
  capacity: __t.f64(),
  demand: __t.f64(),
  currentPower: __t.f64().name("current_power"),
  occupancy: __t.u32(),
  status: __t.string(),
  failed: __t.bool(),
  loadShed: __t.f64().name("load_shed"),
  powerRatio: __t.f64().name("power_ratio"),
  x: __t.f64(),
  y: __t.f64(),
});
