// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  conn: __t.string(),
  name: __t.string(),
  role: __t.string(),
  hasCursor: __t.bool().name("has_cursor"),
  cursorLng: __t.f64().name("cursor_lng"),
  cursorLat: __t.f64().name("cursor_lat"),
  joinedAt: __t.timestamp().name("joined_at"),
  lastSeen: __t.timestamp().name("last_seen"),
});
