// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  Node,
  Edge,
  TickSummary,
} from "./types";

export default {
  tick: __t.u64(),
  get nodes() {
    return __t.array(Node);
  },
  get edges() {
    return __t.array(Edge);
  },
  get summary() {
    return TickSummary;
  },
};
