// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  itemKey: __t.string().primaryKey().name("item_key"),
  kind: __t.string(),
  payload: __t.string(),
  position: __t.u32(),
  version: __t.u32(),
  updatedBy: __t.identity().name("updated_by"),
  updatedByName: __t.string().name("updated_by_name"),
  updatedAt: __t.timestamp().name("updated_at"),
});
