// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  tick: __t.u64(),
  supply: __t.f64(),
  demand: __t.f64(),
  deficit: __t.f64(),
  powerRatio: __t.f64().name("power_ratio"),
  green: __t.u32(),
  amber: __t.u32(),
  red: __t.u32(),
  updatedAt: __t.timestamp().name("updated_at"),
});
