// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Edge = __t.object("Edge", {
  id: __t.string(),
  source: __t.string(),
  target: __t.string(),
  type: __t.string(),
});
export type Edge = __Infer<typeof Edge>;

export const Node = __t.object("Node", {
  id: __t.string(),
  name: __t.string(),
  type: __t.string(),
  priority: __t.string(),
  capacity: __t.f64(),
  demand: __t.f64(),
  currentPower: __t.f64(),
  occupancy: __t.u32(),
  status: __t.string(),
  failed: __t.bool(),
  loadShed: __t.f64(),
  powerRatio: __t.f64(),
  x: __t.f64(),
  y: __t.f64(),
});
export type Node = __Infer<typeof Node>;

export const SimState = __t.object("SimState", {
  id: __t.u32(),
  tick: __t.u64(),
  supply: __t.f64(),
  demand: __t.f64(),
  deficit: __t.f64(),
  powerRatio: __t.f64(),
  green: __t.u32(),
  amber: __t.u32(),
  red: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type SimState = __Infer<typeof SimState>;

export const TickSummary = __t.object("TickSummary", {
  supply: __t.f64(),
  demand: __t.f64(),
  deficit: __t.f64(),
  powerRatio: __t.f64(),
  green: __t.u32(),
  amber: __t.u32(),
  red: __t.u32(),
});
export type TickSummary = __Infer<typeof TickSummary>;

