// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClearStateReducer from "../clear_state_reducer";
import PublishStateReducer from "../publish_state_reducer";

export type ClearStateParams = __Infer<typeof ClearStateReducer>;
export type PublishStateParams = __Infer<typeof PublishStateReducer>;

